EBGInfra={declareNamespace:function(a){for(var b=window.EBG,a=a.split("."),c=0;c<a.length;c++){var d=a[c],e=b[d];e||(e=b[d]={});b=e}},declareClass:function(a,b){a.prototype.constructor=a;if(b)a.__superClass=b,a.__basePrototypePending=!0,EBG._resolveInheritance(a);return a},runTimed:function(a,b,c,d){return setTimeout(function(){b.apply(a,c)},d)},setInterval:function(a,b,c,d){return setInterval(function(){b.apply(a,c)},d)},clearInterval:function(a){clearInterval(a)},_resolveInheritance:function(a){if(a.__basePrototypePending){var b=
a.__superClass;EBG._resolveInheritance(b);var b=b.prototype,c=a.prototype,d;for(d in b)c[d]=c[d]||b[d];delete a.__basePrototypePending}},callSuperConstructor:function(a,b,c){(a=a.__superClass)&&(c?a.apply(b,c):a.apply(b));return b},callSuperFunction:function(a,b,c,d){if(a=a.__superClass)var e=a.prototype[c];if(e instanceof Function)return d?e.apply(b,d):e.apply(b)},typeOf:function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array||!(a instanceof Object)&&"[object Array]"==Object.prototype.toString.call(a)||
"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if(!(a instanceof Object)&&("[object Function]"==Object.prototype.toString.call(a)||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call")))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},isFunc:function(a){return"function"==EBG.typeOf(a)},isDefined:function(a){return"undefined"!=
EBG.typeOf(a)},hasValue:function(a){return null!=a&&"undefined"!=EBG.typeOf(a)},isObj:function(a){return"object"==EBG.typeOf(a)},isBool:function(a){return"boolean"==EBG.typeOf(a)},format:function(a){for(var b=1;b<arguments.length;b++)a=a.replace(RegExp("\\{"+(b-1)+"\\}","gi"),""+arguments[b]);return a},throwEx:function(a){throw{name:"",message:a};},mergeObj:function(a,b,c){var c=!!c,d;for(d in a)if(a.hasOwnProperty(d)&&(!b.hasOwnProperty(d)||c))b[d]=a[d]},cloneObj:function(a){if(!EBG.isObj(a))return null;
var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=EBG.isObj(a[c])?EBG.cloneObj(a[c]):a[c]);return b},combinePaths:function(a,b){a=a||"";b=b||"";a&&"/"!=a[a.length-1]&&(a+="/");var c=a;b&&(c+=b);return c},px:function(a){return EBG.format("{0}px",a)},strEQ:function(a,b,c){return a&&b?c?a===b:a.toLowerCase()===b.toLowerCase():!1},indexOfArray:function(a,b){for(var c=0;c<a.length;c++)if(a[c]==b)return c;return-1},isGlobalDef:function(a,b){var c="undefined"!=eval("typeof("+a+")");b&&c&&(c=eval(a+"=="+b));
return c},numberToEnum:function(a,b){var c="",d;for(d in b)if(b.hasOwnProperty(d)&&b[d]===a){c=d;break}return c}};EBG=window.EBG||{};EBGInfra.mergeObj(EBGInfra,EBG,!1);
EBG.VideoInteraction={STARTED:"ebVideoStarted",PERCENT_25_PLAYED:"eb25Per_Played",PERCENT_50_PLAYED:"eb50Per_Played",PERCENT_75_PLAYED:"eb75Per_Played",FULLPLAY:"ebVideoFullPlay",MUTE:"ebVideoMute",UNMUTE:"ebVideoUnmute",PAUSE:"ebVideoPause",REPLAY:"ebVideoReplay",UNMUTED:"ebVideoUnmuted",FULLSCREEN_START:"ebFSStart",FULLSCREEN_END:"ebFSEnd",FULLSCREEN_MUTE:"ebFSVideoMute",FULLSCREEN_PAUSE:"ebFSVideoPause",SLIDER_DRAGGED:"ebSliderDragged",VIDEO_PLAY_DURATION:"ebVideoPlayDuration",VIDEO_ASSET_DURATION:"ebVideoAssetDuration",
FULLSCREEN_DURATION:"ebFSVideoPlayDuration",FULLSCREEN_ASSET_DURATION:"ebFSVideoAssetDuration"};
EBG.EBMessage={REQ_INIT:"reqInit",INIT:"ebInit",INITDONE:"ebInitDone",SHOW_DEFAULT_IMAGE:"ebShowDefaultImage",CLICKTHROUGH:"ebclickthrough",VERSION_TRACKING_IMPRESSION:"ebversiontrackingimpression",USER_ACTION_COUNTER:"ebCIUserActionCounter",AUTOMATIC_EVENT_COUNTER:"ebCIAutomaticEventCounter",START_TIMER:"ebCIStartTimer",UPDATE_TIMER:"ebUpdateTimer",STOP_TIMER:"ebCIStopTimer",START_VIDEO_TIMER:"ebStartVideoTimer",STOP_VIDEO_TIMER:"ebendvideotimer",VIDEO_INTERACTION:"ebVideoInteraction",VIDEO_LOAD:"ebVideoLoad",
INIT_VIDEO_LOADER:"ebInitVideoLoader",VIDEO_FS_OPEN:"ebVideoFSOpen",VIDEO_FS_CLOSE:"ebVideoFSClose",VIDEO_FS_AUTO_CLOSE:"ebVideoFSAutoClose",INIT_EXPANSION_PARAMS:"ebInitExpansionParams",EXPAND:"ebExpandPanel",EXPAND_DONE:"ebExpandDone",COLLAPSE:"ebCollapsePanel",COLLAPSE_DONE:"ebCollapseDone"};
EBG.INNERIFRAMEMessage={LOADED:"ebInnerIframeLoaded",INIT:"ebInitInnerIframe",EBO:"ebO",GLOBALPARAMS:"ebGlobalParams",CONTINUE_SENDING:"ContinueSending",NOT_LASTMSG:"NotLastMsg",LASTMSG:"LastMsg",ADCONFIG_REQUEST:"AdConfig_Request",SECRET_TAGS:"Secret_Tags"};
EBG.FS={EB_VERSION_TRACKING_IMPRESSION:"ebversiontrackingimpression",EB_CLICKTHROUGH:"ebclickthrough",EB_CI_USER_ACTION_COUNTER:"ebciuseractioncounter",EB_CI_AUTOMATIC_EVENT_COUNTER:"ebciautomaticeventcounter",EB_VIDEO_INTERACTION:"ebvideointeraction",EB_START_TIMER:"ebstarttimer",EB_END_TIMER:"ebendtimer",EB_CI_START_TIMER:"ebcistarttimer",EB_CI_STOP_TIMER:"ebcistoptimer",EB_UPDATE_TIMER:"ebupdatetimer",EB_START_VIDEO_TIMER:"ebstartvideotimer",EB_STOP_VIDEO_TIMER:"ebendvideotimer",EB_PAGE_LOAD:"ebpageload",
EB_COMMAND:"ebcommand",EB_MSG:"ebmsg",EB_EXPAND_PANEL:"ebexpandpanel",EB_COLLAPSE_PANEL:"ebcollapsepanel",EB_SET_STATE:"ebsetstate",EB_RESET_STATE:"ebresetstate",EB_MOUSE_TRACKER:"ebmousetracker",EB_MOUSE_MOVE:"ebmousemove",EB_TEST_DC:"ebtestdc",EB_CLOSE_AD:"ebclosead",EB_REPLAY_AD:"ebreplayad",EB_REPLAY_EXP:"ebreplayexp",EB_LOAD_RICH_BANNER:"ebloadrichbanner",EB_SHOW_RICH_BANNER:"ebshowrichbanner",EB_INIT_VIDEO_LOADER:"ebinitvideoloader",EB_VIDEO_LOAD:"ebvideoload",EB_VIDEO_LOAD_AND_PLAY:"ebvideoloadandplay",
EB_FULL_SCREEN_OPEN:"ebfullscreenopen",EB_FULL_SCREEN_CLOSE:"ebfullscreenclose",EB_FULL_SCREEN_AUTO_CLOSE:"ebfullscreenautoclose",EB_VIDEO_FS_OPEN:"ebvideofsopen",EB_VIDEO_FS_CLOSE:"ebvideofsclose",EB_VIDEO_FS_AUTO_CLOSE:"ebvideofsautoclose",EB_GET_JS_VAR:"ebgetjsvar",EB_GET_ALL_JS_VARS:"ebgetalljsvars",EB_SET_JS_VAR:"ebsetjsvar"};EBG.ActionType={USER:"user",AUTO:"auto"};EBG.SingleExpInteractions={PANELS_VIEWED:"ebPanelsViewed",AUTO_SHOW:"autoshow",DURATION:"duration"};
EBG.adTypes={RichBannerHtml5:"Html5Banner",SEBannerHtml5:"Html5SEBanner",StdBanner:"StdBanner",Banner:"Banner",SEBanner:"SEBanner",ExpBanner:"ExpBanner"};EBG.WindowTarget={BLANK:"_blank",SELF:"_self",PARENT:"_parent",TOP:"_top"};
EBG.Const={OUTER_DIV:"eyeDiv",DATACAPTURE:"/BurstingPipe/BurstingDataCapturePipe.asp",AKAMAIFCS_PLUID_9:"rtmp://flv.stream.atwola.com/flash/flv/mm",AKAMAIFCS_PLUID_43:"rtmp://eyeblaster.fcod.msecnd.net/vod/a10061/e1",AKAMAIFCS_PLUID_42_45:"rtmp://cp57388.edgefcs.net/ondemand",AKAMAI_DEFAULT:"rtmp://cp16207.edgefcs.net/ondemand"};EBG.PanelPositionType={PAGE_RELATIVE_PERCENTAGE:0,BANNER_RELATIVE_PIXELS:1,PAGE_RELATIVE_PIXELS:2};EBG.PanelCorner={TOP_LEFT:1,TOP_RIGHT:2,BOTTOM_LEFT:3,BOTTOM_RIGHT:4};
EBG.AnimationType={NONE:"none",LINEAR:"linear",EASE_OUT:"easeout",EASE_OUT_SNAP:"easeoutsnap"};EBG.ExpandCollapseMethod={SEBanner:"clip",ExpBanner:"resize"};EBG.AnimationDefaults={easeOutCoefficient:0.1,stepTime:10,linearSteps:50,animationType:EBG.AnimationType.NONE,snapThreshold:10};EBG.declareNamespace("Events");EBG.Events.EventTiming={BEFORE:"BEFORE",ONTIME:"ONTIME",AFTER:"AFTER",ONTIME_AND_AFTER:"ONTIME_AND_AFTER"};
EBG.Events.EventNames={CREATE_AD:"CREATE_AD",CREATE_ADAPTOR:"CREATE_ADAPTOR",CREATE_INT_MGR:"CREATE_INT_MGR",CREATE_POSITIONING_HELPER:"CREATE_POSITIONING_HELPER",SHOW_AD:"SHOW_AD",ADD_CREATIVES:"ADD_CREATIVES",ADD_BANNER_DEFAULT_IMAGE_CREATIVE:"ADD_BANNER_DEFAULT_IMAGE_CREATIVE",ADD_BANNER_DEFAULT_FLASH_CREATIVE:"ADD_BANNER_DEFAULT_FLASH_CREATIVE",ADD_BANNER_RICH_FLASH_CREATIVE:"ADD_BANNER_RICH_FLASH_CREATIVE",ADD_PANEL_RICH_FLASH_CREATIVE:"ADD_PANEL_RICH_FLASH_CREATIVE",SHOW_BANNER_RICH_FLASH_CREATIVE:"SHOW_BANNER_RICH_FLASH_CREATIVE",
SHOW_PANEL_RICH_FLASH_CREATIVE:"SHOW_PANEL_RICH_FLASH_CREATIVE",PAGE_LOAD:"PAGE_LOAD",COLLECT_TIMERS:"COLLECT_TIMERS",PAGE_UNLOAD:"PAGE_UNLOAD",PAGE_BEFORE_UNLOAD:"PAGE_BEFORE_UNLOAD",PAGE_HIDE:"PAGE_HIDE",PAGE_RESIZE:"PAGE_RESIZE",PAGE_SCROLL:"PAGE_SCROLL",PAGE_FOCUS:"PAGE_FOCUS",PAGE_BLUR:"PAGE_BLUR",INTERACTION_REPORT_REMOTE_SERVERS:"INTERACTION_REPORT_REMOTE_SERVERS",START_TIMER:"START_TIMER",STOP_TIMER:"STOP_TIMER",UPDATE_TIMER:"UPDATE_TIMER",HANDLE_COUNTER_INTERACTION:"HANDLE_COUNTER_INTERACTION",
DEFAULT_CLICK:"DEFAULT_CLICK",EXPAND:"EXPAND",COLLAPSE:"COLLAPSE",USER_INTERACTION:"USER_INTERACTION",MOUSE_OVER:"MOUSE_OVER",MOUSE_OUT:"MOUSE_OUT",MOUSE_MOVE:"MOUSE_MOVE",USER_INITIATED_VIDEO:"USER_INITIATED_VIDEO",DWELL_UNIQUE:"DWELL_UNIQUE",DWELL_VIDEO_START:"DWELL_VIDEO_START",DWELL_VIDEO_STOP:"DWELL_VIDEO_STOP",CREATIVE_CONTAINER_READY:"CREATIVE_CONTAINER_READY",RICH_FLASH_PLAYED:"RICH_FLASH_PLAYED",REPLAY_AD:"REPLAY_AD",BANDWITH_DETECTED:"BANDWITH_DETECTED",FULL_SCREEN_START:"FULL_SCREEN_START",
FULL_SCREEN_END:"FULL_SCREEN_STOP",ANIMATE_PANEL:"ANIMATE_PANEL",CLOSE_AD:"CLOSE_AD"};EBG.Events.EbEventNames={PAGE_LOAD:EBG.Events.EventNames.PAGE_LOAD};EBG.Events.EventSubscription=function(a,b,c){this.eventName=a;this.callback=b;this.callbackBinding=c?c:null};
EBG.Events.EventSubscription.prototype={dispatcherFilters:null,timing:EBG.Events.EventTiming.ONTIME,isElementEvent:!1,elementId:"",isValid:function(){return EBG.isFunc(this.callback)&&(!this.callbackBinding||EBG.isObj(this.callbackBinding))},toString:function(){return EBG.format("EventSubscription: eventName={0}, timing={1}, callback={2}, callbackBinding={3}, dispatcherFilters={4}",this.eventName,this.timing,EBG.typeOf(this.callback),EBG.typeOf(this.callbackBinding),EBG.typeOf(this.dispatcherFilters))}};
EBG.declareClass(EBG.Events.EventSubscription,null);EBG.Events.Event=function(a){this.name=a;this.creationTime=+new Date};EBG.Events.Event.prototype={dispatcher:null,eventData:null,timing:null,toString:function(){return EBG.format("Event: name={0}, creationTime={1}, dispatcher={2}, eventData={3}",this.name,this.creationTime,EBG.typeOf(this.dispatcher),EBG.typeOf(this.eventData))}};EBG.declareClass(EBG.Events.Event,null);EBG.Events.EventManager=function(){this._subscriptions={}};
EBG.Events.EventManager.prototype={_subscriptions:{},subscribeToEvent:function(a){if(a.isValid())if(a.isElementEvent)EBG.adaptor&&EBG.adaptor.subscribeToEventOnElement(a.eventName,a.elementId,a.callback);else{var b=this._subscriptions[a.eventName]=this._subscriptions[a.eventName]||{},c;for(c in EBG.Events.EventTiming)EBG.Events.EventTiming.hasOwnProperty(c)&&(b[c]=b[c]||[]);b[a.timing].push(a);EBG.adaptor&&EBG.adaptor.hasEvent(a.eventName)&&EBG.adaptor.subscribeToEvent(a.eventName)}},dispatchEvent:function(a){var b=
!1;switch(a.timing){case EBG.Events.EventTiming.BEFORE:case EBG.Events.EventTiming.ONTIME:case EBG.Events.EventTiming.AFTER:b=this._dispatchEventByTiming(a,a.timing);break;case EBG.Events.EventTiming.ONTIME_AND_AFTER:b=(b=this._dispatchEventByTiming(a,EBG.Events.EventTiming.ONTIME))||this._dispatchEventByTiming(a,EBG.Events.EventTiming.AFTER);break;default:b=(b=(b=this._dispatchEventByTiming(a,EBG.Events.EventTiming.BEFORE))||this._dispatchEventByTiming(a,EBG.Events.EventTiming.ONTIME))||this._dispatchEventByTiming(a,
EBG.Events.EventTiming.AFTER)}return b},attachToAdaptor:function(){EBG.adaptor.setListener(this.dispatchEvent,this)},_dispatchEventByTiming:function(a,b){var c=this._subscriptions[a.name];if(!c)return!1;for(var c=c[b],d=!1,e=0;e<c.length;e++){var f=this._dispatchEventToSubscription(a,c[e]);if(EBG.isBool(f)&&!f){d=!0;break}}return d},_dispatchEventToSubscription:function(a,b){var c=b.dispatcherFilters;if(EBG.isObj(c))for(var d in c)if(c.hasOwnProperty(d)){var e=c[d],f=!0,g=d.split("."),h=a.dispatcher;
if(h)for(var i=0;i<g.length;i++){var h=h[g[i]],j=i==g.length-1;if(!h||j&&h!==e){f=!1;break}}if(!f)return null}c=null;d=b.callback;if(EBG.isFunc(d)){e=[a];try{c=d.apply(b.callbackBinding,e)}catch(k){}}return c}};EBG.declareClass(EBG.Events.EventManager,null);EBG.eventMgr=EBG.eventMgr||new EBG.Events.EventManager;EBG.declareNamespace("Adaptors");EBG.Adaptors.TagNames={DIV:"div",IFRAME:"iframe",IMG:"img",SCRIPT:"script",OBJECT:"object",EMBED:"embed"};EBG.Adaptors.InjectionMethod={APPEND:"append",INSERT_BEFORE:"insertBefore"};
EBG.Adaptors.WindowProp={top:"top",left:"left",location:"location",menubar:"menubar",width:"width",height:"height"};EBG.Adaptors.StdWebAdaptor=function(){this._setEvents()};EBG.Adaptors.StdWebAdaptor.onEnvEvent=function(){EBG.adaptor._handleEvent.apply(EBG.adaptor,arguments)};
EBG.Adaptors.StdWebAdaptor.prototype={_environmentEvents:{},_logicalEvents:{},_subscribedEvents:{},_subscribedEventsOnElement:[],_listener:null,_listenerBinding:null,initInnerModules:function(a,b,c){if(!this.browser)this.browser=new EBG.Adaptors.Browser(a,b,c);if(!this.flash)this.flash=EBG.Adaptors.FlashDetector?new EBG.Adaptors.FlashDetector:null},copy:function(a){for(var b in this._subscribedEvents)this._subscribedEvents.hasOwnProperty(b)&&(this._removeEventListener(window,this._environmentEvents[b].name,
EBG.Adaptors.StdWebAdaptor.onEnvEvent),a.subscribeToEvent(b));for(b=0;b<this._subscribedEventsOnElement.length;b++){var c=this._subscribedEventsOnElement[b],d=c.elementId,e=c.eventName,c=c.callback,f=this.getElementById(d);f&&(this._removeEventListener(f,e,c),a.subscribeToEventOnElement(e,d,c))}},intMonitorExist:function(){return EBG.isPreview&&top.ebHandleFsCommandsPrev},notifyIntMonitor:function(a){top.ebHandleFsCommandsPrev(a.command,a.args,a.objName,a.adId)},hasEvent:function(a){return!!this._environmentEvents[a]},
generateElementId:function(a,b){return EBG.format("eb{0}_{1}",a,b)},_getTags:function(a,b){EBG.isGlobalDef("JSON");var c="";if(b&&a.tagName==EBG.Adaptors.TagNames.SCRIPT&&a.text&&!a.attributes)b.push(a);else{c="";a.attributes&&(this._setObjDefaultAttributes(a),c=this._getObjAttributesStr(a));c=EBG.format("<{0} {1}>",a.tagName,c);a.innerHTML&&(c+=a.innerHTML);a.text&&(c+=a.text);a.params&&(c+=this._getObjParamsStr(a));if(a.children)for(var d=0;d<a.children.length;d++)c+=this._getTags(a.children[d],
b);c+=EBG.format("</{0}>",a.tagName)}return c},writeReportingIFrame:function(a,b,c){this.inject({tagName:EBG.Adaptors.TagNames.IFRAME,attributes:{id:a,src:b,style:{width:"0px",height:"0px"},frameborder:0}},EBG.Adaptors.InjectionMethod.APPEND,this.getElementById(c))},writeScript:function(a,b,c){try{this.inject({tagName:EBG.Adaptors.TagNames.SCRIPT,attributes:{id:a,name:a,src:b}},EBG.Adaptors.InjectionMethod.APPEND,this.getElementById(c))}catch(d){}},write:function(a){this._documentWrite(this._getTags(a))},
inject:function(a,b,c){var d=c.ownerDocument.createElement(a.tagName);if(a.attributes){this._setObjDefaultAttributes(a);for(var e in a.attributes)EBG.isObj(a.attributes[e])?this._setStyleToElem(d,a.attributes[e]):d.setAttribute(e,a.attributes[e])}e="";if(a.innerHTML)e=a.innerHTML;var f=[];if(a.children)for(var g=0;g<a.children.length;g++)e+=EBG.adaptor._getTags(a.children[g],f);if(e)d.innerHTML=e;if(a.text)d.text=a.text;switch(b){case EBG.Adaptors.InjectionMethod.INSERT_BEFORE:c.parentNode.insertBefore(d,
c);break;default:c.appendChild(d)}for(g=0;g<f.length;g++)this.inject(f[g],b,c)},addInlineDOM:function(a,b){this.inject(a,EBG.Adaptors.InjectionMethod.APPEND,this.getElementById(b))},setInnerHtml:function(a,b){a.innerHTML=b},_setStyleToElem:function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a.style[c]=b[c])},setListener:function(a,b){this._listener=a;this._listenerBinding=b},subscribeToEvent:function(a){if(this.hasEvent(a)&&!this._subscribedEvents[a]){var b=this._environmentEvents[a];this._addEventListener(b.inCurWin?
window:this.getPageWin(),b.name,EBG.Adaptors.StdWebAdaptor.onEnvEvent);this._subscribedEvents[a]={}}},subscribeToEventOnElement:function(a,b,c){var d=!1,e=this.getDisplayWin().document.getElementById(b);e||(d=!0);for(var f=this._subscribedEventsOnElement.length,g=0;g<f;g++)if(this._subscribedEventsOnElement[g].elementId==b&&this._subscribedEventsOnElement[g].eventName==a){d=!0;break}d||(this._addEventListener(e,a,c),this._subscribedEventsOnElement[f]={elementId:b,eventName:a,callback:c})},_addEventListener:function(a,
b,c){if("load"==b&&this.isPageLoaded())setTimeout(function(){c({type:"load"})},5);else if(EBG.isDefined(window["on"+b])||EBG.isDefined(document["on"+b]))window.addEventListener?a.addEventListener(b,c,!1):window.attachEvent&&a.attachEvent("on"+b,c)},_removeEventListener:function(a,b,c){window.removeEventListener?a.removeEventListener(b,c,!1):window.detachEvent&&a.detachEvent("on"+b,c)},_checkIfPropExist:function(a,b){return a&&0<=a?EBG.format(", {0}={1}",b,a):""},openPage:function(a,b){var c=EBG.WindowTarget.BLANK,
d="titlebar=1,resizable=1,scrollbars=1,directories=0,toolbar=1,status=1";if(b)c=b.target,d+=this._checkIfPropExist(b.yPos,EBG.Adaptors.WindowProp.top),d+=this._checkIfPropExist(b.xPos,EBG.Adaptors.WindowProp.left),d+=this._checkIfPropExist(b.showAddressBar,EBG.Adaptors.WindowProp.location),d+=this._checkIfPropExist(b.showMenuBar,EBG.Adaptors.WindowProp.menubar),d+=this._checkIfPropExist(b.width,EBG.Adaptors.WindowProp.width),d+=this._checkIfPropExist(b.height,EBG.Adaptors.WindowProp.height);window.open(a,
c,d)},reportToRemoteServerUsingImage:function(a){this.ReportingImg=new Image;this.ReportingImg.src=a},reportToRemoteServer:function(a,b){if(a){var b=EBG.isBool(b)?b:!0,c=!1;try{if(this._isXMLHttpRequestSupported()){var d=new XMLHttpRequest;if(void 0!==d.withCredentials){d.open("GET",a,b);try{d.send()}catch(e){if(b)throw e;}c=!0}else c=!1}else if(window.XDomainRequest){var f=new XDomainRequest;f.open("GET",a);f.send();c=!0}}catch(g){c=!1}c||this.reportToRemoteServerUsingImage(a)}},getElementById:function(a,
b){b=b?b:this.getDisplayWin();return b.document.getElementById(a)},supportsPageLoadEvents:function(){return!this.browser.isOpera()},getHostName:function(a){return(a?a:this.getDisplayWin()).location.hostname},getDisplayWin:function(){return window},getPageWin:function(){return window},inInnerIframe:function(){return!1},inPlacementIframe:function(){return!1},_setEvents:function(){this.supportsPageLoadEvents&&(this._setEvent(EBG.Events.EventNames.PAGE_LOAD,"load"),this._setEvent(EBG.Events.EventNames.PAGE_UNLOAD,
"unload",!0),this._setEvent(EBG.Events.EventNames.PAGE_BEFORE_UNLOAD,"beforeunload",!0),this._setEvent(EBG.Events.EventNames.PAGE_HIDE,"pagehide",!0))},_setEvent:function(a,b,c){this._environmentEvents[a]={name:b,inCurWin:c?c:!1};this._logicalEvents[b]=a},_documentWrite:function(a){document.write(a)},_isXMLHttpRequestSupported:function(){var a=window.XMLHttpRequest?new XMLHttpRequest:null;return a&&EBG.isBool(a.withCredentials)},isPageLoaded:function(){if(this._isPageLoaded)return!0;this._isPageLoaded=
EBGInfra.isDefined(window.gEBMainWindow)&&EBGInfra.isDefined(gEBMainWindow.downloadMgr)&&gEBMainWindow.isPageLoaded||EBGInfra.isDefined(this._isPageLoaded)?!0:!1;if(!this._isPageLoaded&&this.getDisplayWin().document.readyState)this._isPageLoaded="complete"==this.getDisplayWin().document.readyState;return EBG.adaptor._isPageLoaded},_handleEvent:function(a){a=this._logicalEvents[a.type];switch(a){case EBG.Events.EventNames.PAGE_LOAD:this._isPageLoaded=!0;break;case EBG.Events.EventNames.PAGE_RESIZE:EBG.adaptor.inInnerIframe()&&
this.serving.rehidePlacementIframe()}a&&(a=new EBG.Events.Event(a),EBG.isFunc(this._listener)&&this._listener.call(this._listenerBinding,a))},_getDefaultAttributes:function(a){var b={};switch(a.toLowerCase()){case EBG.Adaptors.TagNames.IFRAME:b={marginheight:"0px",marginwidth:"0px",frameborder:"0",scrolling:"no"}}return b},_getDefaultStyle:function(a){var b={border:"0px",padding:"0px",margin:"0px"};switch(a.toLowerCase()){case EBG.Adaptors.TagNames.DIV:EBG.mergeObj({top:"0px",left:"0px",overflow:"visible",
fontSize:"0px",lineHeight:"0px",textAlign:"left"},b,!0)}return b},_setObjDefaultAttributes:function(a){var b=this._getDefaultAttributes(a.tagName);EBG.mergeObj(a.attributes,b,!0);b.style=this._getDefaultStyle(a.tagName);a.attributes.style&&EBG.mergeObj(a.attributes.style,b.style,!0);a.attributes=b},_getObjParamsStr:function(a){var a=a.params,b="",c;for(c in a)a.hasOwnProperty(c)&&(b+=EBG.format("<PARAM name='{0}' value='{1}'>",c,a[c]));return b},_getObjAttributesStr:function(a){var a=a.attributes,
b="",c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];if(EBG.isObj(d)){var e=d,d="",f;for(f in e)if(e.hasOwnProperty(f)){var g=e[f];"textAlign"==f&&(f="text-align");d+=EBG.format("{0}:{1}; ",f,g)}}b+=EBG.format(" {0}='{1}'",c,d)}return b},_XXgetObjAttributesStr:function(a){var b=a.attributes,c="",d;for(d in b)if(b.hasOwnProperty(d)){var e=b[d];EBG.isObj(e)&&this._setStyleToElem(a,e);c+=EBG.format(" {0}='{1}'",d,e)}return c},handleEvent:function(a){this._handleEvent(a)},setElemStyle:function(a,b,c){a.style[b]=
c}};EBG.declareClass(EBG.Adaptors.StdWebAdaptor,null);EBG.Adaptors.Browser=function(a,b,c){this.set(a,b,c)};
EBG.Adaptors.Browser.prototype={_platform:0,_browserType:0,_browserVer:0,_browserTypes:{NON_SUPPORTED:0,IE:1,FF:2,NN:3,SAFARI:4,CHROME:5,AOL:6,OPERA:7},_platformTypes:{NON_SUPPORTED:0,WIN_95:1,WIN_98:2,WIN_2000:3,WIN_XP:4,WIN_ME:5,WIN_NT:6,MAC:7,WIN_VISTA:8,WIN_7:9,IPHONE:10,IPAD:11,IPOD:12,ANDROID_2_TAB:13,ANDROID_3_TAB:14,BLACKBARRY_5:15,WIN_MOBILE_7:16,ANDROID_2_MOBILE:17,ANDROID_3_MOBILE:18},set:function(a,b,c){a=a?a:this._platformTypes.NON_SUPPORTED;b=b?b:this._browserTypes.NON_SUPPORTED;this._platform=
a;this._browserType=b;this._browserVer=c?c:0},getVersion:function(){return this._browserVer},isIE:function(){return this._browserType==this._browserTypes.IE||this._browserType==this._browserTypes.AOL},isStrictType:function(){return this.isIE()?"CSS1Compat"==document.compatMode:!1},isFF:function(){return this._browserType==this._browserTypes.FF},isSafari:function(){return this._browserType==this._browserTypes.SAFARI},isChrome:function(){return this._browserType==this._browserTypes.CHROME},isOpera:function(){return this._browserType==
this._browserTypes.OPERA},isMac:function(){return this.platform==this._platformTypes.MAC}};EBG.Adaptors.FlashDetector=function(){this._init()};
EBG.Adaptors.FlashDetector.prototype={version:0,_init:function(){var a=-1;try{a=(new ActiveXObject("Shockwaveflash.Shockwaveflash.7")).GetVariable("$version"),a=this._splitFlashMajorMinorVersions(a),a=Number(a)}catch(b){}if(-1==a)try{var c=0,d=0,e=0;if(null!=navigator.plugins&&0<navigator.plugins.length){if(navigator.plugins["Shockwave Flash"]){var f=navigator.plugins["Shockwave Flash"].description.split(" "),g=f[2].split("."),c=g[0],d=g[1],e=f[3];""==e&&(e=f[4]);isNaN(e[0])&&(e=e.substring(1));0<
e.indexOf("d")&&(e=e.substring(0,e.indexOf("d")))}a=Number(c+"."+d+e)}}catch(h){}if(!isNaN(a))this.version=a},_splitFlashMajorMinorVersions:function(a){if(a)return a=a.split(" ")[1].split(","),EBG.format("{0}.{1}{2}",a[0],a[1],a[2])}};EBG.declareNamespace("Interactions");
EBG.Interactions.SystemInts={CLICK:"_eyeblaster",AD_DURATION:"ebAdDuration",REPLAY:"ebReplay",CLOSE:"ebClose",DEFAULT_CLICK:"ebDefaultClick",USER_INTERACTION:"ebUserInteraction",USER_INITIATED_VIDEO:"ebUserInitiatedVideo",UNIQUE_VIDEO_STARTED:"ebUniqueVideoStarted",ABOVE_THE_FOLD:"ebAboveTheFold",ABOVE_THE_FOLD_DURATION:"ebAboveTheFoldDuration",BELOW_THE_FOLD:"ebBelowTheFold",VISIBILITY_DURATION:"ebVisibilityDuration",CUSTOM_VISIBILITY_DURATION:"ebCustomVisibilityDuration",DWELL_TIME:"ebDwellTime",
DWELL_UNIQUE:"ebUniqueDwell",RICH_FLASH_PLAYED:"ebRichFlashPlayed",INT_DURATION:"ebIntDuration"};EBG.Interactions.VideoInteractionOrder=[EBG.VideoInteraction.STARTED,EBG.VideoInteraction.PERCENT_25_PLAYED,EBG.VideoInteraction.PERCENT_50_PLAYED,EBG.VideoInteraction.PERCENT_75_PLAYED,EBG.VideoInteraction.FULLPLAY];EBG.Interactions.Categories={SYSTEM:2,VIDEO:1,CUSTOM:0};EBG.Interactions.InitiationTypes={AUTO:"auto",USER:"user"};EBG.Interactions.InteractionTypes={COUNTER:"Counter",TIMER:"Timer"};
EBG.Interactions.checkURL=function(a){var b=a.toLowerCase();-1==b.indexOf("http://")&&-1==b.indexOf("https://")&&-1==b.indexOf("ftp://")&&-1==b.indexOf("aim:")&&-1==b.indexOf("mailto:")&&(a=0==b.indexOf("/")?"http://"+EBG.adaptor.getHostName()+a:"http://"+a);return a};EBG.Interactions.RemoteServersData=function(){};EBG.Interactions.RemoteServersData.prototype={networkUrl:null,agencyUrl:null};EBG.declareClass(EBG.Interactions.RemoteServersData,null);
EBG.Interactions.InteractionData=function(a,b,c){this.reportingName=a;this.adUId=b;this.category=c};EBG.Interactions.InteractionData.prototype={initiationType:EBG.Interactions.InitiationTypes.AUTO,category:EBG.Interactions.Categories.SYSTEM,isPanel:!1};EBG.declareClass(EBG.Interactions.InteractionData,null);EBG.Interactions.CounterInteractionData=function(a,b,c){EBG.callSuperConstructor(EBG.Interactions.CounterInteractionData,this,[a,c,b]);this.remoteServers=new EBG.Interactions.RemoteServersData};
EBG.Interactions.CounterInteractionData.prototype={reportImmediately:!1,countAsClick:!1,remoteServers:null,clickURL:null,numLeftToReport:10,state:null};EBG.declareClass(EBG.Interactions.CounterInteractionData,EBG.Interactions.InteractionData);EBG.Interactions.TimerInteractionData=function(a,b,c){this.reportingName=a;EBG.callSuperConstructor(EBG.Interactions.TimerInteractionData,this,[a,c,b])};EBG.Interactions.TimerInteractionData.prototype={value:0,startTime:0,idleDuration:0};
EBG.declareClass(EBG.Interactions.TimerInteractionData,EBG.Interactions.InteractionData);EBG.Interactions.Interaction=function(){};
EBG.Interactions.Interaction.prototype={unique:!0,_escapeInteractionName:function(a){a=a.toString();a=a.replace(/\~/ig,"_");a=a.replace(/\^/ig,"_");a=a.replace(/\|/ig,"_");return escape(a)},_buildReportFormat:function(a,b,c,d){d||(d=0);return EBG.format("{0}{2}{1}{3}{1}{4}{1}{5}{6}{7}{8}{9}",EBG.Interactions.InteractionManager.charIntDelimeter,EBG.Interactions.InteractionManager.charAdFieldsDelimeter,this._escapeInteractionName(this.interactionData.reportingName),c,d,a,this.unique?1:0,b,this.interactionData.category,
this.interactionData.isPanel?1:0)}};EBG.Interactions.CounterInteraction=function(a){EBG.callSuperConstructor(EBG.Interactions.CounterInteraction,this);this.interactionData=a?a:new EBG.Interactions.CounterInteractionData};
EBG.Interactions.CounterInteraction.prototype={type:EBG.Interactions.InteractionTypes.COUNTER,handle:function(a){var b=this.interactionData,c=!0;0==b.numLeftToReport||EBG.isPreview?c=!1:b.numLeftToReport--;var d=!1,e=!1;if(b.clickData){var f=b.clickData,g="undefined"==typeof f.tmpData.windowWasOpen?!1:f.tmpData.windowWasOpen,h=f.tmpData?f.tmpData.clickUrl:null,i=h||f.jumpUrl;if(i&&!g){if(e=c&&(f.tmpData.isClick||this._isEBClick()))this._isEBClick()&&(h||(i=""),d=!0),g=b.reportingName.toLowerCase()==
EBG.Interactions.SystemInts.DEFAULT_CLICK.toLowerCase(),h=f.tmpData.isProductClick?f.tmpData.isClick?1:2:f.tmpData.isClick?1:0,i=""==i?"":EBG.Interactions.checkURL(i),i=this._getBannerRedirectUrl(i,h,g,f.tmpData.clickedVersion);i=""==i?"":EBG.Interactions.checkURL(i);-1==f.target.indexOf(EBG.WindowTarget.BLANK)?(b.reportImmediately=!0,EBG.runTimed(this,this._openPage,[i,f],1E3)):this._openPage(i,f)}else this._isEBClick()&&(c=!1)}b="";c&&(this._handleRemoteServers(),d||(b=this._getReportingData(a,
e)));return b},getClickTagUrl:function(){var a="";if(EBG.isPreview)a=EBG.isInWorkshop?EBG.format("ReportPage_{0}.html",HTMLPageVer):this.interactionData.clickData.jumpUrl;else{var a=this._getBannerRedirectUrl(),a=EBG.format("{0}/ReportPage{1}.html?ebReportURL={2}$$ebImpressionID={3}",ebBigS,EBG.reportPageVer,escape(a),EBG.Ads.Ad.Fn.getRandFromAdUId(this.interactionData.adConfig.uid)),b=-1;EBG.adaptor.browser.isIE()&&(b=9<=EBG.adaptor.browser.getVersion()?4096:2048,b-=a.length);b=this._getReportPageTrackingUrls(b);
a+=b}return a},_getReportPageTrackingUrls:function(a){var b="$$ebTURLs=[";if(-1!=a){if(b.length>=a)return"";a-=b.length}for(var c=this.interactionData.adConfig.clickTrackingUrls,d=0;d<c.length;d++){var e=EBG.format('{0}"{1}"',0!=d?",":"",c[d]);if(-1!=a){if(e.length>=a)break;a-=e.length}b+=e}return b+"]"},_openPage:function(a,b){EBG.adaptor.openPage(a,b)},_getReportingData:function(a,b){var c=0,d=0;b||(c=this.interactionData.clickData&&this.interactionData.clickData.tmpData.isClick?1:0,d=this.interactionData.initiationType==
EBG.Interactions.InitiationTypes.USER?1:0);c=this._buildReportFormat(c,d,0,a);this.unique=!1;return c},_getBannerRedirectUrl:function(a,b,c,d){var c=EBG.isBool(c)?c:!1,e=this.interactionData.adConfig,f=EBG.Ads.Ad.Fn.getAdIdFromAdUId(this.interactionData.adConfig.uid),f=EBG.protocol+EBG.combinePaths(EBG.bs,EBG.format("BurstingPipe/adServer.bs?cn=brd&Page={0}&PluID={1}&Pos={2}&EyeblasterID={3}",e.page,EBG.pluId,e.rnd,f));void 0!=b&&(f=EBG.format("{0}&clk={1}",f,b));e.massVersioning.adVersions&&(f=d?
f+EBG.format("&vid={0}&vcl=1",d):f+EBG.format("&vid={0}",EBG.Ads.Ad.Fn.getVersionToReport(e.massVersioning.adVersions)));a&&(a=a.replace(/#/g,"%23"),f+=EBG.format("&rtu=$${0}$$",a));e.massVersioning.targetAudienceId&&(f+=EBG.format("&ta={0}",e.massVersioning.targetAudienceId));e.massVersioning.deliveryGroupId&&(f+=EBG.format("&dg={0}",e.massVersioning.deliveryGroupId));e.sPublisherPlacementId&&(f+=EBG.format("&pc={0}",e.sPublisherPlacementId));c||(f+="&di=0");e.sID&&(f+=EBG.format("&sessionid={0}",
e.sID));return f},_handleRemoteServers:function(){if(!EBG.isPreview&&this.interactionData.remoteServers){var a=this.interactionData.remoteServers,b=new EBG.Events.Event(EBG.Events.EventNames.INTERACTION_REPORT_REMOTE_SERVERS);b.dispatcher=this;b.timing=EBG.Events.EventTiming.BEFORE;b.eventData={remoteServers:a};EBG.eventMgr.dispatchEvent(b)||(a.networkUrl&&(b=this._replaceRSTokens(a.networkUrl),EBG.adaptor.reportToRemoteServerUsingImage(b)),a.agencyUrl&&(a=this._replaceRSTokens(a.agencyUrl),EBG.adaptor.reportToRemoteServerUsingImage(a)))}},
_replaceRSTokens:function(a){try{a=a.replace(/\[ebInteraction\]/ig,this.interactionData.reportingName),a=a.replace(/\[ebInteractionNum\]/ig,EBG.intMgr.adsData[this.interactionData.adConfig.uid].numOfInteractions)}catch(b){}return a},_getReportingPage:function(){var a=this.interactionData.adConfig.page,a=a.replace(/\~/ig,"_"),a=a.replace(/\^/ig,"_"),a=a.replace(/\|/ig,"_");return escape(a)},_isEBClick:function(){return this.interactionData&&(EBG.strEQ(this.interactionData.reportingName,EBG.Interactions.SystemInts.CLICK)||
EBG.strEQ(this.interactionData.reportingName,EBG.Interactions.SystemInts.DEFAULT_CLICK))}};EBG.declareClass(EBG.Interactions.CounterInteraction,EBG.Interactions.Interaction);EBG.Interactions.StdInteractionManager=function(){this.adsData=EBG.intMgr?EBG.intMgr.adsData:{};this.adsIntQueues=EBG.intMgr?EBG.intMgr.adsIntQueues:{}};
EBG.Interactions.StdInteractionManager.prototype={copy:function(a){this.adsIntQueues=a.adsIntQueues;this.adsData=a.adsData},initAdData:function(a){var b=a.uid;this.adsIntQueues[b]=[];adData=this.adsData[b]={adConfig:a,isUserInteractionOccur:!1,isClickOccur:!1,isProductClicked:[],numOfInteractions:0,videoState:{},assetsTimers:{}};adData[EBG.Interactions.InteractionTypes.COUNTER]={};adData[EBG.Interactions.InteractionTypes.TIMER]={};adData.adConfig.isStdAd||this._addSystemInteractions(a)},addInteraction:function(a){var b=
a.interactionData.adUId,c=this.adsData[b];if(c)c[a.type][a.interactionData.reportingName]=a,a.interactionData.adConfig=this.adsData[b].adConfig},getClickTag:function(a){return(a=this._getCounterInteraction(EBG.Interactions.SystemInts.CLICK,a))?a.getClickTagUrl():""},getClickTarget:function(a){return(a=this._getCounterInteraction(EBG.Interactions.SystemInts.CLICK,a))?a.interactionData.clickData.target:""},handleCounterInteraction:function(a,b,c,d,e,f){var g=this.adsData[b].adConfig.isStdAd;"undefined"==
typeof f&&(f=!0);var c=c||0,h=this._getCounterInteraction(a,b);if(d)d=h.interactionData,d.initiationType=EBG.Interactions.InitiationTypes.USER,g||this._handleUserInteraction(b,d);if(h){d=h.interactionData;if(d.clickData)d.clickData.tmpData=e;e=new EBG.Events.Event(EBG.Events.EventNames.HANDLE_COUNTER_INTERACTION);e.dispatcher=this;e.timing=EBG.Events.EventTiming.BEFORE;e.eventData={interaction:h};if(!EBG.eventMgr.dispatchEvent(e)){g||this._handleSpecialInteractions(a,b,c);if(d.clickData){if(1==d.clickData.fClose){var i=
new EBG.Events.Event(EBG.Events.EventNames.CLOSE_AD);e.dispatcher=this;EBG.eventMgr.dispatchEvent(i)}d.clickData.tmpData.isClick=d.countAsClick&&!this.adsData[b].isClickOccur;if(d.clickData.tmpData.isClick)this.adsData[b].isClickOccur=!0;d.clickData.tmpData.isProductClick=d.countAsClick&&d.clickData.tmpData.clickedVersion&&!this.adsData[b].isProductClicked[d.clickData.tmpData.clickedVersion];d.clickData.tmpData.isProductClick&&(this.adsData[b].isProductClicked[d.clickData.tmpData.clickedVersion]=
!0)}f=f?h.handle(c):"";if(d.clickData&&!EBG.isPreview){if(d.clickData.tmpData.isClick){h=this.adsData[b].adConfig.clickTrackingUrls;for(i=0;i<h.length;i++)EBG.adaptor.reportToRemoteServerUsingImage(h[i])}d.clickData.tmpData.isProductClick&&d.clickData.tmpData.clickedVerUrl&&EBG.adaptor.reportToRemoteServerUsingImage(d.clickData.tmpData.clickedVerUrl)}this.adsData[b].numOfInteractions++;g||(this._handleUserInteraction(b,d),f&&this._handleReportData(b,d,f),this._handleSpecialInteractions(a,b,c),f&&
!this._isReportDataInQueue(b,f)&&this.reportInteractionQueues());e.timing=EBG.Events.EventTiming.ONTIME_AND_AFTER;EBG.eventMgr.dispatchEvent(e)}}},_getCounterInteraction:function(a,b){if(this.adsData[b]&&this.adsData[b][EBG.Interactions.InteractionTypes.COUNTER]&&this.adsData[b][EBG.Interactions.InteractionTypes.COUNTER][a])return this.adsData[b][EBG.Interactions.InteractionTypes.COUNTER][a]}};EBG.declareClass(EBG.Interactions.StdInteractionManager,null);EBG.declareNamespace("Ads");
EBG.Ads.Ad=function(a){this._adConfig=a;this._adConfig.isStdAd=this._isStdAd();this._fixPage();this._updateURLs();this._show()};
EBG.Ads.Ad.prototype={_adConfig:null,_isStdAd:function(){return!0},_counterInteractionHandler:function(a){try{var b=a.eventData.intName;if(!b)b=EBG.Interactions.SystemInts.CLICK;a.eventData.clickUrl=this._replaceURLTokens(a.eventData.clickUrl);a.eventData.clickedVerUrl=this._replaceURLTokens(a.eventData.clickedVerUrl);EBG.intMgr.handleCounterInteraction(b,this._adConfig.uid,0,null,a.eventData,"undefined"!=typeof a.eventData.handleClickInt?a.eventData.handleClickInt:!0)}catch(c){}},_versionTrackingImpressionHandler:function(a){try{if(a.eventData.impTrackingUrls&&
!EBG.isPreview)for(var b=0;b<a.eventData.impTrackingUrls.length;b++){var c=a.eventData.impTrackingUrls[b];c&&(c=this._replaceURLTokens(c),EBG.adaptor.reportToRemoteServerUsingImage(c))}}catch(d){}},_show:function(){try{var a=new EBG.Events.Event(EBG.Events.EventNames.SHOW_AD);a.dispatcher=this;a.timing=EBG.Events.EventTiming.BEFORE;EBG.eventMgr.dispatchEvent(a);EBG.intMgr.initAdData(this._adConfig);this._addSystemInteractions();this._subscribeToEvents();this._canShow()&&!this._adConfig.showOnlyImage?
(this._addVideoInteractions(),this._addCustomInteractions(),this._addCreatives()):this.showDefaultImage&&this.showDefaultImage();a.timing=EBG.Events.EventTiming.ONTIME_AND_AFTER;EBG.eventMgr.dispatchEvent(a)}catch(b){}},_canShow:function(){return!0},_onPlayHandler:function(){this._adConfig.arrOnPlayEvents&&this._executeEvents(this._adConfig.arrOnPlayEvents)},_onDownloadHandler:function(){this._adConfig.arrOnStartDnlEvents&&this._executeEvents(this._adConfig.arrOnStartDnlEvents)},_collectUrl:function(){if(!EBG.isPreview&&
this._adConfig.shouldCollectUrl)try{EBG.adaptor.reportToRemoteServer(EBG.format("{0}{1}/BurstingPipe/adServer.bs?cn=curl&ai={2}&url=$${3}$$",EBG.protocol,EBG.bs,this._adConfig.adId,top.document.URL))}catch(a){}},_executeEvents:function(a){for(var b=0;b<a.length;b++){var c,d=this._replaceURLTokens(a[b].url);switch(a[b].typeId){case 3:c="ebPlayScript"+b;EBG.adaptor.writeScript(EBG.adaptor.generateElementId(c,this._adConfig.uid),d,this._adConfig.placeHolderId);break;case 5:c="ebDnlScript"+b;EBG.adaptor.writeScript(EBG.adaptor.generateElementId(c,
this._adConfig.uid),d,this._adConfig.placeHolderId);break;case 4:c="ebPlayIFR"+b;EBG.adaptor.writeReportingIFrame(EBG.adaptor.generateElementId(c,this._adConfig.uid),d,this._adConfig.placeHolderId);break;case 6:c="ebDnlIFR"+b,EBG.adaptor.writeReportingIFrame(EBG.adaptor.generateElementId(c,this._adConfig.uid),d,this._adConfig.placeHolderId)}}},_addSystemInteractions:function(){try{var a=this._adConfig.interactions[EBG.Interactions.SystemInts.CLICK];if(a){var b=EBG.Interactions.Categories.SYSTEM;this._addCounterInteraction(EBG.Interactions.SystemInts.CLICK,
b);this._adConfig.interactions[EBG.Interactions.SystemInts.DEFAULT_CLICK]=EBG.cloneObj(a);this._addCounterInteraction(EBG.Interactions.SystemInts.DEFAULT_CLICK,b)}}catch(c){}},_addCounterInteraction:function(a,b,c){var d=this._adConfig.interactions[a],b=new EBG.Interactions.CounterInteractionData(a,b,this._adConfig.uid);b.initiationType=d.nInitiated?EBG.Interactions.InitiationTypes.USER:EBG.Interactions.InitiationTypes.AUTO;b.countAsClick=d.fClick;if(d.agencyURL)b.remoteServers.agencyUrl=d.agencyURL;
if(d.networkURL)b.remoteServers.networkUrl=d.networkURL;this._adjustClickTarget(a);b.clickData=d;b.reportImmediately=c?!0:!1;a=new EBG.Interactions.CounterInteraction(b);EBG.intMgr.addInteraction(a)},_addVideoInteractions:function(){},_addCustomInteractions:function(){},_adjustClickTarget:function(a){var a=this._adConfig.interactions[a],b;switch(a.target){case 0:b=EBG.WindowTarget.SELF;break;case 2:b=EBG.WindowTarget.TOP;break;default:b=EBG.WindowTarget.BLANK}a.target=b},_subscribeToEvents:function(){this._subscribeToAdEvent(EBG.EBMessage.CLICKTHROUGH,
this._counterInteractionHandler);this._subscribeToAdEvent(EBG.EBMessage.VERSION_TRACKING_IMPRESSION,this._versionTrackingImpressionHandler);this._subscribeToAdEvent(EBG.Events.EventNames.DEFAULT_CLICK,this._counterInteractionHandler);this._subscribeToAdEvent(EBG.Events.EventNames.ADD_CREATIVES,this._onAddCreativesHandler,EBG.Events.EventTiming.ONTIME);this._subscribeToAdEvent(EBG.Events.EventNames.SHOW_AD,this._onDownloadHandler,EBG.Events.EventTiming.ONTIME);this._subscribeToAdEvent(EBG.Events.EventNames.SHOW_AD,
this._onPlayHandler,EBG.Events.EventTiming.AFTER);this._subscribeToAdEvent(EBG.Events.EventNames.SHOW_AD,this._collectUrl,EBG.Events.EventTiming.AFTER)},_onAddCreativesHandler:function(a){try{if(!EBG.Initializer._getAdClass({tn:this._adConfig.templateName}).requiresIframeBust||EBG.adaptor.serving&&EBG.adaptor.serving.detectServingMode(!0)==EBG.Adaptors.ServingMode.SCRIPT){var b=a.dispatcher._adConfig.placeHolderId;if(b){var c=EBG.adaptor.getDisplayWin().document.getElementById(b);if(c)c.style.backgroundImage=
"",c.onclick=function(){}}}}catch(d){}},_onAdCreativesAdded:function(){var a=new EBG.Events.Event(EBG.Events.EventNames.AD_CREATIVES_ADDED);a.dispatcher=this;EBG.eventMgr.dispatchEvent(a)},_fixPage:function(){var a=this._adConfig.page,a=a.replace(/\~/ig,"_"),a=a.replace(/\^/ig,"_"),a=a.replace(/\|/ig,"_"),a=escape(a);this._adConfig.page=a},_updateURLs:function(){for(var a=this._adConfig.clickTrackingUrls,b=0;b<a.length;b++)a[b]=this._replaceURLTokens(a[b]);var a=this._adConfig.interactions,c;for(c in a)if(a.hasOwnProperty(c))a[c].agencyURL=
this._replaceURLTokens(a[c].agencyURL),a[c].networkURL=this._replaceURLTokens(a[c].networkURL),a[c].jumpUrl=this._replaceURLTokens(a[c].jumpUrl)},getAdId:function(){return this._adConfig.adId},_replaceURLTokens:function(a){var b=this._adConfig;try{a&&(a=a.replace(/\[ebRandom\]/ig,b.rnd),a=a.replace(/\[timestamp\]/ig,b.rnd),a=a.replace(/\[%tp_adid%\]/ig,b.adId),a=a.replace(/\[%tp_flightid%\]/ig,b.placementId),a=a.replace(/\[%tp_campaignid%\]/ig,b.campaignId));if(!a||!b.sUrlTokens)return a;if(!EBG.isObj(b.objURLTokens))b.oURLTokens=
this._pairsToObj(b.sUrlTokens,"$$");for(var c in b.oURLTokens)b.oURLTokens.hasOwnProperty(c)&&(a=a.replace(RegExp("\\[%"+c+"%\\]","ig"),b.oURLTokens[c]))}catch(d){}return a},_pairsToObj:function(a,b){for(var c={},d=unescape(a).split(b),e=0;e<d.length;e++)try{if(d[e]){var f=d[e].indexOf("="),g=d[e].substr(0,f),h=d[e].substr(f+1);c[g]=escape(h)}}catch(i){}return c},_subscribeToAdEvent:function(a,b,c){a=new EBG.Events.EventSubscription(a,b,this);a.dispatcherFilters={"_adConfig.rnd":this._adConfig.rnd};
if(c)a.timing=c;EBG.eventMgr.subscribeToEvent(a)},_getCDIUrl:function(){var a=EBG.format("{0}{1}/BurstingPipe/adServer.bs?cn=cdi&ai={2}&p={3}&pluid={4}&pc={5}&ord={6}",EBG.protocol,EBG.bs,this._adConfig.adId,this._adConfig.page,EBG.pluId,this._adConfig.sPublisherPlacementId,this._adConfig.rnd),b=this._adConfig.massVersioning.targetAudienceId;b&&(a+=EBG.format("&ta={0}",b));(b=this._adConfig.massVersioning.deliveryGroupId)&&(a+=EBG.format("&dg={0}",b));return a},showDefaultImage:function(){var a=!this._adConfig.imageOnly,
b=this._adConfig.showOnlyImage||this._adConfig.imageOnly?EBG.combinePaths(ebResourcePath,this._adConfig.defaultImagePath):this._getCDIUrl(),b={tagName:EBG.Adaptors.TagNames.IMG,attributes:{id:EBG.format("ebDefaultImg_{0}",this._adConfig.uid),src:b,width:this._adConfig.width,height:this._adConfig.height,style:{width:this._adConfig.width,height:this._adConfig.height},title:this._adConfig.title?this._adConfig.title:""}};if(a?this._adConfig.interactions[EBG.Interactions.SystemInts.DEFAULT_CLICK].jumpUrl:
this._adConfig.interactions[EBG.Interactions.SystemInts.CLICK].jumpUrl)b.attributes.onclick=EBG.format('EBG.Ads.Ad.Fn.onDefaultImageClick("{0}", {1})',this._adConfig.uid,a),EBG.mergeObj({cursor:"pointer; cursor: hand"},b.attributes.style);a=new EBG.Events.Event(EBG.Events.EventNames.ADD_BANNER_DEFAULT_IMAGE_CREATIVE);a.eventData=b.attributes.id;a.dispatcher=this;a.timing=EBG.Events.EventTiming.BEFORE;if(!EBG.eventMgr.dispatchEvent(a)){var b=EBG.adaptor._getTags(b),c=EBG.adaptor.getElementById(this._adConfig.placeHolderId);
EBG.adaptor.setInnerHtml(c,b);a.timing=EBG.Events.EventTiming.ONTIME_AND_AFTER;EBG.eventMgr.dispatchEvent(a)}}};EBG.declareClass(EBG.Ads.Ad,null);
EBG.Ads.Ad.Fn={getAdIdFromAdUId:function(a){return a.split("_")[0]},getRandFromAdUId:function(a){return a.split("_")[1]},onDefaultImageClick:function(a,b){try{var c=b?new EBG.Events.Event(EBG.Events.EventNames.DEFAULT_CLICK):new EBG.Events.Event(EBG.EBMessage.CLICKTHROUGH);c.eventData=b?{intName:EBG.Interactions.SystemInts.DEFAULT_CLICK}:{intName:EBG.Interactions.SystemInts.CLICK};c.dispatcher=EBG.ads[a];EBG.eventMgr.dispatchEvent(c)}catch(d){}},getVersionToReport:function(a){return-1<a.indexOf(",")?
"m":a},getAdVersions:function(a){for(var b="",a=a.adVersions.split(","),c=0;c<a.length;c++)b&&(b+=","),b+=a[c];return b}};EBG.Ads.StdBanner=function(a){EBG.callSuperConstructor(EBG.Ads.StdBanner,this,[a])};EBG.Ads.StdBanner.requiresIframeBust=!1;
EBG.Ads.StdBanner.prototype={_flashResID:null,_CCs:{},_canShow:function(){var a=!1;this._adConfig.flashResPath?EBG.adaptor.flash.version>=this._adConfig.flashVer&&(a=!0):this._adConfig.imageOnly=!0;return a},_writeCreativeElements:function(){try{var a={resPath:this._adConfig.flashResPath,resId:this._flashResID,width:this._adConfig.width,height:this._adConfig.height,play:"true",wmode:"opaque"},b=EBG.adaptor.generateElementId("StdBannerDiv",this._adConfig.uid),c={tagName:EBG.Adaptors.TagNames.DIV,attributes:{id:b,
dir:"ltr",style:{width:this._adConfig.width,height:this._adConfig.height}},children:this._CCs[this._flashResID].buildCreativeContainerJson(a)},d=new EBG.Events.Event(EBG.Events.EventNames.ADD_CREATIVES);d.dispatcher=this;d.eventData={tagsObj:c};d.timing=EBG.Events.EventTiming.BEFORE;if(!EBG.eventMgr.dispatchEvent(d))EBG.adaptor.addInlineDOM(c,this._adConfig.placeHolderId),d.timing=EBG.Events.EventTiming.ONTIME,EBG.eventMgr.dispatchEvent(d),d.timing=EBG.Events.EventTiming.AFTER,EBG.eventMgr.dispatchEvent(d)}catch(e){}},
_addCreatives:function(){this._flashResID=EBG.adaptor.generateElementId("StdBannerFlash",this._adConfig.uid);this._CCs[this._flashResID]=new EBG.FlashCC(this._adConfig);this._writeCreativeElements();var a=EBG.adaptor.getElementById(this._adConfig.placeHolderId);a&&(EBG.adaptor.setElemStyle(a,"width",EBG.px(this._adConfig.width)),EBG.adaptor.setElemStyle(a,"height",EBG.px(this._adConfig.height)))}};EBG.declareClass(EBG.Ads.StdBanner,EBG.Ads.Ad);EBG.declareNamespace("CreativeContainer");
EBG.CreativeContainer=function(a){this._adConfig=a};EBG.declareClass(EBG.CreativeContainer,null);EBG.declareNamespace("FlashCC");EBG.FlashCC=function(a){EBG.callSuperConstructor(EBG.FlashCC,this,[a]);this.fs={};this._addSupportedFSCommands()};
EBG.FlashCC.prototype={_createIntMonitorObj:function(a,b){return{command:a,args:b,objName:this._flashResID,adId:this._adConfig.adId}},_buildAdditionalResStr:function(){var a="",b=this._adConfig.assets,c;for(c in b)try{var d=b[c],e=EBG.isInWorkshop?d.dsPath:EBG.combinePaths(ebResourcePath,d.dsPath),a=EBG.format("{0}{1}{2}={3}",a,a?"&":"",c,e)}catch(f){}return a},_getSmartVersioningFlashVars:function(){var a="",a="";this._adConfig.massVersioning.adVersions?this._adConfig.sv2DisplayMap&&(a=EBG.format("&ebAdVersions={0}&ebAdMap={1}&ebResPath={2}&ebAdSVBasePath={3}",
EBG.Ads.Ad.Fn.getAdVersions(this._adConfig.massVersioning),this._adConfig.sv2DisplayMap,EBG.isInWorkshop?"":ebResourcePath,this._adConfig.massVersioning.adBasePath)):this._adConfig.svXML&&(a=EBG.isGlobalDef("ebAdXmlPath")&&ebAdXmlPath?ebAdXmlPath:EBG.isInWorkshop?this._adConfig.svXML:EBG.combinePaths(ebResourcePath,this._adConfig.svXML),a=EBG.format("&ebAdXML={0}",a));return a},_getFlashParams:function(){var a=EBG.adaptor.getHostName(),b=EBG.intMgr.getClickTag(this._adConfig.uid),c=EBG.intMgr.getClickTarget(this._adConfig.uid),
d=EBG.adaptor.browser.isIE()?"":this._flashResID+"_DoFSCommand";return EBG.format("ebDomain={0}&ebAdID={1}&clickTag={2}&clickTAG={2}&clicktag={2}&ebFSCmdHandler={3}&clickTARGET={4}&ebFlashID={5}{6}&{7}",a,this._adConfig.adId,escape(b),d,c,this._flashResID,this._getSmartVersioningFlashVars(),this._buildAdditionalResStr())},buildCreativeContainerJson:function(a){var b,c,d=null;b=["transparent","opaque","window"];for(c=0;3>c;c++)b[b[c]]=b[c];this._flashResID=a.resId;this._src=a.resPath;this._weight=
a.weight;c=EBG.format("EBG.ads['{0}']._CCs['{1}']",this._adConfig.uid,this._flashResID);d=EBG.format("function {0}_DoFSCommand(command,args)",this._flashResID);d+=EBG.format("{ try{ if(!args||args=='null')args='';command = command.replace(/FSCommand:/ig,''); return {0}._handleMessage(command,args,'{1}');}catch(e){if(window.mmFSExceptionAlert)mmFSExceptionAlert('Command: '+command+'\\nargs: '+args.toString()+'\\n\\nexception in DoFS func:\\n'+e.message)}}",c,this._flashResID);c={tagName:EBG.Adaptors.TagNames.SCRIPT,
text:d+"function ebIsFlashExtInterfaceExist(){return true;}"};d=EBG.format("try{{0}_DoFSCommand(command,args);}catch(e){}",this._flashResID);d={tagName:EBG.Adaptors.TagNames.SCRIPT,attributes:{"for":this._flashResID,event:"FSCommand(command,args)"},text:d};b={tagName:EBG.Adaptors.TagNames.OBJECT,attributes:{id:this._flashResID,dir:"ltr",name:this._flashResID,style:{textAlign:"left",width:EBG.format("{0}px",a.width),height:EBG.format("{0}px",a.height)},type:"application/x-shockwave-flash",codebase:EBG.format("{0}download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#",
EBG.protocol),version:EBG.format("{0},0,0,0",this._adConfig.flashVer),title:this._adConfig.title?this._adConfig.title:""},params:{play:a.play,wmode:b[a.wmode],menu:"false",movie:EBG.combinePaths(EBG.resourcePath,a.resPath),flashVars:this._getFlashParams(),allowScriptAccess:"always",allowFullScreen:"true"}};if(!EBG.adaptor.browser.isIE())b.attributes.data=EBG.combinePaths(EBG.resourcePath,a.resPath);return 0<a.unique?[b,d]:[b,c,d]},_handleMessage:function(a,b,c){var a=a.replace(/FSCommand:/ig,""),
d=a=a.toLowerCase(),e=b;a==EBG.EBMessage.CLICKTHROUGH&&b&&0==b.indexOf("SV2:")&&-1!=b.indexOf("\u007f")&&(e=b.substring(4),d=a+"sv2");var f=this.fs[d],g=f.mapEvent||d.toLowerCase(),g=new EBG.Events.Event(g);g.dispatcher=this;g.flashResId=c;var c=",",h=!1;switch(d){case EBG.EBMessage.CLICKTHROUGH:g.eventData={};break;case EBG.EBMessage.CLICKTHROUGH+"sv2":case EBG.FS.EB_SET_JS_VAR:c="\u007f";break;case EBG.EBMessage.VERSION_TRACKING_IMPRESSION:h=!0,g.eventData[f.args[0]]=b.split("\u007f")}if(f&&f.args&&
!h&&(g.eventData={adUId:this._adConfig.uid},0<b.length)){d=e.split(c);for(e=0;e<f.args.length;e++)c=f.args[e],h="",e<d.length&&(h='"'==d[e].charAt(0)||"'"==d[e].charAt(0)||"false"==d[e]||"true"==d[e]?eval(d[e]):d[e]),g.eventData[c]=h}if(f){if(f.command)return b=[g.eventData],f.command.call(this,b);EBG.eventMgr.dispatchEvent(g)}EBG.adaptor.intMonitorExist()&&EBG.adaptor.notifyIntMonitor(this._createIntMonitorObj(a,b))},_addSupportedFSCommands:function(){this.fs[EBG.FS.EB_CLICKTHROUGH]={mapEvent:EBG.EBMessage.CLICKTHROUGH};
this.fs[EBG.FS.EB_CLICKTHROUGH+"sv2"]={mapEvent:EBG.EBMessage.CLICKTHROUGH,args:["clickUrl","clickedVersion","clickedVerUrl"]};this.fs[EBG.FS.EB_VERSION_TRACKING_IMPRESSION]={mapEvent:EBG.EBMessage.VERSION_TRACKING_IMPRESSION,args:["impTrackingUrls"]}}};EBG.declareClass(EBG.FlashCC,EBG.CreativeContainer);EBG.declareNamespace("RichFlashCC");EBG.RichFlashCC=function(a){EBG.callSuperConstructor(EBG.RichFlashCC,this,[a])};
EBG.RichFlashCC.prototype={_numOfPlayRetry:0,_addSupportedFSCommands:function(){EBG.callSuperFunction(EBG.RichFlashCC,this,"_addSupportedFSCommands");this.fs[EBG.FS.EB_CLICKTHROUGH]={mapEvent:EBG.EBMessage.CLICKTHROUGH,args:["intName"]};this.fs[EBG.FS.EB_CI_USER_ACTION_COUNTER]={mapEvent:EBG.EBMessage.USER_ACTION_COUNTER,args:["intName"]};this.fs[EBG.FS.EB_CI_AUTOMATIC_EVENT_COUNTER]={mapEvent:EBG.EBMessage.AUTOMATIC_EVENT_COUNTER,args:["intName"]};this.fs[EBG.FS.EB_VIDEO_INTERACTION]={mapEvent:EBG.EBMessage.VIDEO_INTERACTION,
args:["intName","ebmovie"]};this.fs[EBG.FS.EB_START_TIMER]={mapEvent:EBG.EBMessage.START_TIMER,args:["intName","assetId"]};this.fs[EBG.FS.EB_END_TIMER]={mapEvent:EBG.EBMessage.STOP_TIMER,args:["intName","assetId"]};this.fs[EBG.FS.EB_CI_START_TIMER]={mapEvent:EBG.EBMessage.START_TIMER,args:["intName"]};this.fs[EBG.FS.EB_CI_STOP_TIMER]={mapEvent:EBG.EBMessage.STOP_TIMER,args:["intName"]};this.fs[EBG.FS.EB_UPDATE_TIMER]={mapEvent:EBG.EBMessage.UPDATE_TIMER,args:["intName","timerValue"]};this.fs[EBG.FS.EB_START_VIDEO_TIMER]=
{mapEvent:EBG.EBMessage.START_VIDEO_TIMER,args:["intName","ebmovie"]};this.fs[EBG.FS.EB_STOP_VIDEO_TIMER]={mapEvent:EBG.EBMessage.STOP_VIDEO_TIMER,args:["intName","ebmovie"]};this.fs[EBG.FS.EB_PAGE_LOAD]={mapEvent:!1,args:["handlerName"]};this.fs[EBG.FS.EB_COMMAND]={mapEvent:!1,args:["command"]};this.fs[EBG.FS.EB_MSG]={mapEvent:!1,args:["message"]};this.fs[EBG.FS.EB_EXPAND_PANEL]={mapEvent:EBG.EBMessage.EXPAND,args:["panelName"]};this.fs[EBG.FS.EB_COLLAPSE_PANEL]={mapEvent:EBG.EBMessage.COLLAPSE,
args:["panelName"]};this.fs[EBG.FS.EB_SET_STATE]={mapEvent:!1,args:["stateValue"]};this.fs[EBG.FS.EB_RESET_STATE]={mapEvent:!1,args:["stateValue"]};this.fs[EBG.FS.EB_MOUSE_TRACKER]={mapEvent:!1,args:["handlerName"]};this.fs[EBG.FS.EB_MOUSE_MOVE]={mapEvent:!1,args:["handlerName"]};this.fs[EBG.FS.EB_TEST_DC]={mapEvent:!1,args:["strArgs"]};this.fs[EBG.FS.EB_CLOSE_AD]={mapEvent:EBG.Events.EventNames.CLOSE_AD,args:["type"]};this.fs[EBG.FS.EB_REPLAY_AD]={mapEvent:EBG.Events.EventNames.REPLAY_AD,args:["type"]};
this.fs[EBG.FS.EB_REPLAY_EXP]={mapEvent:!1,args:!1};this.fs[EBG.FS.EB_LOAD_RICH_BANNER]={mapEvent:!1,args:!1};this.fs[EBG.FS.EB_SHOW_RICH_BANNER]={mapEvent:!1,args:!1};this.fs[EBG.FS.EB_INIT_VIDEO_LOADER]={mapEvent:EBG.EBMessage.INIT_VIDEO_LOADER,args:"apiPath,stretchToFit,streaming,autoplay,xPos,yPos,width,height,handleClick,newComp".split(",")};this.fs[EBG.FS.EB_VIDEO_LOAD]={mapEvent:EBG.EBMessage.VIDEO_LOAD,args:"apiPath,movieName,mute,volume,buffer,fsmovieName,newComp".split(",")};this.fs[EBG.FS.EB_VIDEO_LOAD_AND_PLAY]=
{mapEvent:!1,args:["strArgs"]};this.fs[EBG.FS.EB_FULL_SCREEN_OPEN]={mapEvent:EBG.EBMessage.FULL_SCREEN_OPEN,args:["apiPath"]};this.fs[EBG.FS.EB_FULL_SCREEN_CLOSE]={mapEvent:EBG.EBMessage.FULL_SCREEN_CLOSE,args:["apiPath"]};this.fs[EBG.FS.EB_FULL_SCREEN_AUTO_CLOSE]={mapEvent:EBG.EBMessage.FULL_SCREEN_AUTO_CLOSE,args:["apiPath"]};this.fs[EBG.FS.EB_VIDEO_FS_OPEN]={mapEvent:EBG.EBMessage.VIDEO_FS_OPEN,args:"apiPath,posSecs,mute,volume,playProg,unMuteHandled".split(",")};this.fs[EBG.FS.EB_VIDEO_FS_CLOSE]=
{mapEvent:EBG.EBMessage.VIDEO_FS_CLOSE,args:!1};this.fs[EBG.FS.EB_VIDEO_FS_AUTO_CLOSE]={mapEvent:EBG.EBMessage.VIDEO_FS_AUTO_CLOSE,args:!1};this.fs[EBG.FS.EB_GET_JS_VAR]={mapEvent:!1,args:["varName"],command:this._ebGetJSVar};this.fs[EBG.FS.EB_GET_ALL_JS_VARS]={mapEvent:!1,args:!1,command:this._ebGetAllJSVars};this.fs[EBG.FS.EB_SET_JS_VAR]={mapEvent:!1,args:["varName","varValue","isString"]}},_ebGetJSVar:function(a){var b=a[0].varName;if(a[0]&&EBG.hasValue(b))return this._adConfig[b]},_ebGetAllJSVars:function(){var a=
{};if(this._adConfig.customJSVars)for(var b in this._adConfig.customJSVars)a[b]=this._adConfig[b];return a},_getFlashParams:function(a){var b=EBG.callSuperFunction(EBG.RichFlashCC,this,"_getFlashParams"),c=this._getDynamicContentRes();EBG.isOfflineDemo&&(a=!1);a=a?a:!1;EBG.isGlobalDef("gfEbForceStreaming")&&(a=1);var d=EBG.isPreview,e=EBG.isOfflineDemo||EBG.isPreview?"":EBG.format("{0}{1}{2}",EBG.protocol,EBG.dataCapture,EBG.Const.DATACAPTURE),f=this._adConfig.campaignId,g=EBG.Const.AKAMAI_DEFAULT,
h="";switch(EBG.pluId){case 42:case 45:g=EBG.Const.AKAMAIFCS_PLUID_42_45;break;case 43:g=EBG.Const.AKAMAIFCS_PLUID_43;break;case 9:h="Type-12/",g=EBG.Const.AKAMAIFCS_PLUID_9}var g=escape(g),i=this._src.indexOf("/",EBG.resourcePath),i=EBG.format("{0}{1}",EBG.fcsVirtualPath,this._src.substring(EBG.resourcePath,i+1));strUrlExtended=EBG.format("&ebNewPreview={0}&ebDCPipe={1}&ebResourcePath={2}&ebCampaignID={3}&ebStreamingAppURL={4}&ebStreamVirtualPath={5}&ebAdIdentifier={6}&ebForcePlayMode={7}&ebPageGUID={8}",
d,e,EBG.isInWorkshop?"":EBG.resourcePath,f,g,i+h,this._adConfig.adId,a,EBG.pageGUID);this._adConfig.testImp&&(strUrlExtended+=EBG.format("&ebPipeParams={0}",escape("t=1")));3!=this._adConfig.FSMute&&(strUrlExtended=1==this._adConfig.FSMute?strUrlExtended+"&ebFLVFSMute=1":strUrlExtended+"&ebFLVFSMute=0");return b+c+strUrlExtended},isAS3:function(){try{var a=EBG.adaptor.getElementById(this._flashResID),b="undefined"!=typeof a.ebGetVars;b&&EBG.adaptor.browser.isSafari()&&(b="undefined"!=typeof a.ebGetVars("xmouse"));
return b}catch(c){return!1}},_getDynamicContentRes:function(){try{var a="",b;for(b in this._adConfig.DynamicContentResources)EBG.isDefined(this._adConfig.DynamicContentResources[b].url)&&(a+=EBG.format("&{0}={1}",b,this._adConfig.DynamicContentResources[b].url));return a}catch(c){return!1}},_getFramesLoaded:function(){var a=0;try{100==this._getPercentLoaded()&&(a=1)}catch(b){var c=EBG.adaptor.getElementById(this._flashResID);if("undefined"!=typeof c.TGetProperty)try{a=c.TGetProperty("/",12)}catch(d){a=
0}}return a},_getPercentLoaded:function(){var a=-1,b=EBG.adaptor.getElementById(this._flashResID);"undefined"!=typeof b.PercentLoaded&&(a=b.PercentLoaded());return a},removeAsset:function(a,b){var c=EBG.adaptor.getElementById(this._flashResID);if(c)a&&this.resize(0,0),this._container=c.parentNode,this._previousInnerHTML=c.parentNode.innerHTML,c=c.parentNode,EBG.adaptor.setInnerHtml(c,""),b&&c.parentNode.removeChild(c)},isReady:function(){var a=0,b=0;if(EBG.adaptor.getElementById(this._flashResID)){var a=
this._getFramesLoaded(),b=this._getPercentLoaded(),c=b*this._weight/100;100==b||614400<c||1<a?(a=new EBG.Events.Event(EBG.Events.EventNames.CREATIVE_CONTAINER_READY),a.dispatcher=this,a.eventData=this._flashResID,EBG.eventMgr.dispatchEvent(a)):EBG.runTimed(this,this.isReady,[],50)}else EBG.runTimed(this,this.isReady,[],50)},resize:function(a,b){if(a&&b){var a=parseInt(a),b=parseInt(b),c=EBG.adaptor.getElementById(this._flashResID);EBG.adaptor.setElemStyle(c,"width",EBG.px(a));EBG.adaptor.setElemStyle(c,
"height",EBG.px(b));EBG.adaptor.setElemStyle(c.parentNode,"width",EBG.px(a));EBG.adaptor.setElemStyle(c.parentNode,"height",EBG.px(b))}},call:function(a,b,c){var d=EBG.adaptor.getElementById(this._flashResID);c||(c="");if(this.isAS3())d[a](b,c);else c=""!=c?EBG.format("{0},{1}",b,c):b,d.SetVariable(a,c)},play:function(){EBG.runTimed(this,this._playTimed,[this._flashResID],10)},_playTimed:function(a){try{if(this._numOfPlayRetry++,5<this._numOfPlayRetry){this._numOfPlayRetry=0;var b=new EBG.Events.Event(EBG.Events.EventNames.REPLAY_AD);
b.dispatcher=this;b.flashResID=a;b.eventData={};b.eventData.cancelReport=!0;b.timing=EBG.Events.EventTiming.ONTIME_AND_AFTER;EBG.eventMgr.dispatchEvent(b)}else EBG.adaptor.getElementById(a).Play()}catch(c){EBG.runTimed(this,this._playTimed,[a],100)}},setProxyParams:function(a,b){for(var c=EBG.adaptor.getElementById(this._flashResID),d=b.split(";"),e=0;e<d.length;e++){var f=d[e].split(",");c.SetVariable(a+":"+f[0],f[1])}},callFlashFunc:function(a,b,c){try{"undefined"==typeof c&&(c="");var d=EBG.adaptor.getElementById(this._flashResID),
e="";if(this.isAS3()){var f=a.lastIndexOf("/"),a=-1!=f?a.substring(0,f):a;if(""!=c)for(var g=c.split(";"),c=0;c<g.length;c++)if(""!=g[c]){var h=g[c].split(","),e=e+h[1];c<g.length-1&&(e+=",")}d[a](b,e)}else""!=c&&this.setProxyParams(a,c),d.TCallLabel(a,b)}catch(i){}}};EBG.declareClass(EBG.RichFlashCC,EBG.FlashCC);EBG.declareNamespace("Initializer");
EBG.Initializer={initialize:function(){var a;if(!(void 0!==a&&a)&&(a=EBG.Initializer._getCurrentServerResponse(),EBG.Initializer._initGlobals(a),EBG.Initializer._initAdaptor(a),EBG.Initializer._initInteractionManager(),EBG.Initializer._updateAdConfig(a),EBG.Initializer._initPositioningHelper(),EBG.Initializer._shouldInitAd(a))){if(!EBG.isDefined(EBG.adaptor.getDisplayWin().EBG))EBG.adaptor.getDisplayWin().EBG=EBG;EBG.Initializer._callExtensionHooks(a);EBG.Initializer._initAd(a)}},_shouldInitAd:function(a){return a.innerIframe||
0==a.ifrm||-1==a.ifrm&&EBG.adaptor.serving&&EBG.adaptor.serving.servingMode!=EBG.Adaptors.ServingMode.IFRAME},_getCurrentServerResponse:function(){for(var a=0,b;a<ebOArr.length;){if((b=ebOArr[a])&&this._getAdClass(b)){ebOArr.splice(a,1);break}a++}return b},_initGlobals:function(a){EBG.isOfflineDemo=EBG.isGlobalDef("gEbfOfflineDemo")?gEbfOfflineDemo:!1;EBG.resourcePath=ebResourcePath;EBG.sms=a.sms?a.sms:"";EBG.fcsVirtualPath=a.fvp?a.fvp:"";EBG.pluId=a.pi;EBG.dataCapture=EBG.bs=a.bs;EBG.protocol=ebPtcl;
EBG.pageGUID=EBG.pageGUID?EBG.pageGUID:a.rnd;EBG.reportPageVer=a.rpv;EBG.html5Ver=a.html5v;EBG.isPreview=!!a.pr;EBG.isInWorkshop=EBG.isGlobalDef("gEbFlyLocal")?gEbFlyLocal:!1;EBG.minZIndex=a.z?a.z:1E4;EBG.eyeDivRefElement=EBG.isGlobalDef("gEbEyeDivRefElement")?gEbEyeDivRefElement:!1;EBG.eventMgr=EBG.eventMgr||new EBG.Events.EventManager;EBG.ads=EBG.ads||{}},_initServingMode:function(a){var b=this._getAdClass(a);if(b.requiresIframeBust){if(a.innerIframe)a.ifrm=EBG.Adaptors.ServingMode.INNER_IFRAME;
if(!a.ifrm||a.soi)a.ifrm=0;EBG.adaptor.initServingMode(a.ifrm);if(EBG.adaptor.inPlacementIframe())EBG.adaptor.serving.ebO=EBG.cloneObj(a),EBG.adaptor.serving.insertInnerIframe(a.phid)}else if(a.ifrm=0,a.tn!=EBG.adTypes.StdBanner&&(EBG.adaptor.initServingMode(a.ifrm,!b.requiresIframeBust),EBG.adaptor.serving.isFIF()||EBG.adaptor.serving.servingMode==EBG.Adaptors.ServingMode.FRIENDLY_IFRAME))try{document.close()}catch(c){}},_callExtensionHooks:function(a){if(a.extensionHooks)for(;0!==a.extensionHooks.length;)a.extensionHooks.pop().apply(null,
[a.adConfig])},getRichestAdaptor:function(){for(var a=[EBG.Adaptors.StdWebAdaptor,EBG.Adaptors.WebAdaptor],b=a.length-1;0<=b;b--)if(a[b])return a[b]},getRichestInteractionManager:function(){for(var a=[EBG.Interactions.StdInteractionManager,EBG.Interactions.InteractionManager],b=a.length-1;0<=b;b--)if(a[b])return a[b]},_initAdaptor:function(a){var b=this.getRichestAdaptor(),c=new EBG.Events.Event(EBG.Events.EventNames.CREATE_ADAPTOR);c.eventData={currentClass:b};c.timing=EBG.Events.EventTiming.BEFORE;
EBG.eventMgr.dispatchEvent(c);if("undefined"==typeof EBG.adaptor||EBG.adaptor.constructor.toString()!=c.eventData.currentClass.toString())b=new c.eventData.currentClass,EBG.adaptor=b;c.timing=EBG.Events.EventTiming.ONTIME_AND_AFTER;EBG.eventMgr.dispatchEvent(c);EBG.adaptor.initInnerModules(a.plt,a.bt,a.bv);this._initServingMode(a);EBG.eventMgr.attachToAdaptor()},_initInteractionManager:function(){newEvent=new EBG.Events.Event(EBG.Events.EventNames.CREATE_INT_MGR);newEvent.eventData={currentClass:this.getRichestInteractionManager()};
newEvent.timing=EBG.Events.EventTiming.BEFORE;EBG.eventMgr.dispatchEvent(newEvent);if("undefined"==typeof EBG.intMgr||EBG.intMgr.constructor.toString()!=newEvent.eventData.currentClass.toString()){var a=new newEvent.eventData.currentClass;EBG.intMgr=a}newEvent.timing=EBG.Events.EventTiming.ONTIME_AND_AFTER;EBG.eventMgr.dispatchEvent(newEvent)},_initPositioningHelper:function(){try{if(EBG.Positioning&&EBG.Positioning.PositionManager){newEvent=new EBG.Events.Event(EBG.Events.EventNames.CREATE_POSITIONING_HELPER);
newEvent.eventData=EBG.Positioning.PositionManager;newEvent.timing=EBG.Events.EventTiming.BEFORE;EBG.eventMgr.dispatchEvent(newEvent);if(!EBG.posHelper)EBG.posHelper=new newEvent.eventData;newEvent.timing=EBG.Events.EventTiming.ONTIME_AND_AFTER;EBG.eventMgr.dispatchEvent(newEvent)}}catch(a){}},_initAd:function(a){var b=this._getAdClass(a);newEvent=new EBG.Events.Event(EBG.Events.EventNames.CREATE_AD);newEvent.eventData={currentClass:b,adConfig:a.adConfig};newEvent.timing=EBG.Events.EventTiming.BEFORE;
EBG.eventMgr.dispatchEvent(newEvent);b=new newEvent.eventData.currentClass(a.adConfig);newEvent.timing=EBG.Events.EventTiming.ONTIME_AND_AFTER;EBG.eventMgr.dispatchEvent(newEvent);EBG.ads[a.adConfig.uid]=b;if(EBGInfra.isDefined(EBG.BWDetection)&&EBGInfra.isDefined(window.gEBMainWindow)&&EBGInfra.isDefined(gEBMainWindow.ebBW)&&EBGInfra.isDefined(gEBMainWindow.ebBW.checked))EBG.BWDetection.speed=gEBMainWindow.ebBW.speed,EBG.BWDetection.checked=!0;if(a.adConfig.pckAssets){var b=0,c;for(c in a.adConfig.pckAssets)b++;
0<b&&!EBG.BWDetection.checking&&!EBG.BWDetection.checked&&EBG.BWDetection.init()}},_getAdClass:function(a){var b;switch(a.tn){case EBG.adTypes.RichBannerHtml5:b=EBG.Ads.RichBannerHtml5;break;case EBG.adTypes.SEBannerHtml5:b=EBG.Ads.SEBannerHtml5;break;case EBG.adTypes.StdBanner:b=EBG.Ads.StdBanner;break;case EBG.adTypes.Banner:b=EBG.Ads.RichBanner;break;case EBG.adTypes.SEBanner:b=EBG.Ads.SEBanner;break;case EBG.adTypes.ExpBanner:b=EBG.Ads.ExpBanner}return b},_updateAdConfig:function(a){a.adConfig.rnd=
a.rnd;a.adConfig.uid=EBG.format("{0}_{1}",a.adConfig.adId,a.adConfig.rnd);a.adConfig.placeHolderId=a.phid;a.adConfig.sUrlTokens=a.ut;if(!a.adConfig.clickTrackingUrls)a.adConfig.clickTrackingUrls=[];a.ncu&&a.adConfig.clickTrackingUrls.push(a.ncu);if(a.soi)a.adConfig.showOnlyImage=a.soi;a.adConfig.imageOnly=!1;a.adConfig.page=a.p;a.adConfig.massVersioning={targetAudienceId:a.ta&&"-1"!=a.ta?a.ta:"",deliveryGroupId:a.dg&&"-1"!=a.dg?a.dg:"",adVersions:a.av?a.av:"",adBasePath:a.abp?a.abp:""};a.adConfig.mobileSDK=
a.sdk?a.sdk:"";if("undefined"==typeof a.adConfig.openWindow)a.adConfig.openWindow=!0;this._updateAdConfigToHandleOpenWindow(a);a.adConfig.arrOnStartDnlEvents=a.osde;a.adConfig.arrOnPlayEvents=a.ope;a.adConfig.optOut=a.oo?a.oo:0;a.adConfig.sPublisherPlacementId=a.ppi?a.ppi:"";a.adConfig.width=a.w?a.w:"";a.adConfig.height=a.h?a.h:"";a.adConfig.shouldCollectUrl=a.cu?a.cu:0;a.adConfig.sID=a.sid?a.sid:"";a.adConfig.dlm=a.dlm?a.dlm:3;a.adConfig.testImp=a.t?!0:!1;a.adConfig.usercookie=a.usercookie?a.usercookie:
""},_updateAdConfigToHandleOpenWindow:function(a){a.adConfig.bsPath=EBG.bs;a.adConfig.pluId=EBG.pluId;a.adConfig.protocol=EBG.protocol;a.adConfig.isPreview=!!a.pr}};try{EBG.Initializer.initialize()}catch(e$$30){};
